// Generates tokens.css and tokens.ts from tokens.json. No dependencies.
// Run: pnpm --dir packages/design-tokens build   (CI fails if the generated files are stale)
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const dir = dirname(fileURLToPath(import.meta.url))
const t = JSON.parse(readFileSync(join(dir, 'tokens.json'), 'utf8'))
const kebab = (s) => s.replace(/\//g, '-')
const pct = (n) => `${+(n / 100).toFixed(4)}em`
const px = (n) => `${n}px`

const css = []
const ts = []
const push = (name, value) => css.push(`  --${name}: ${value};`)

for (const [k, v] of Object.entries(t.color)) push(`color-${kebab(k)}`, v)
for (const [k, v] of Object.entries(t.space)) push(`space-${k}`, px(v))
for (const [k, v] of Object.entries(t.radius)) push(`radius-${k}`, px(v))
for (const [k, v] of Object.entries(t.shadow)) push(`shadow-${k}`, v)
for (const [k, v] of Object.entries(t.font.family)) push(`font-family-${k}`, `"${v}", system-ui, sans-serif`.replace(/system-ui, sans-serif$/, k === 'mono' ? 'ui-monospace, monospace' : 'system-ui, sans-serif'))
for (const [name, s] of Object.entries(t.font.style)) {
  push(`font-${name}-family`, `var(--font-family-${s.family})`)
  push(`font-${name}-size`, px(s.size))
  push(`font-${name}-weight`, String(s.weight))
  push(`font-${name}-line-height`, px(s.lineHeight))
  push(`font-${name}-letter-spacing`, pct(s.letterSpacingPct))
}
for (const [k, v] of Object.entries(t.layout)) if (!k.startsWith('$')) push(`layout-${k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())}`, px(v))

// Utility classes so a text style can be applied as one class: className="text-body-m"
const textClasses = Object.entries(t.font.style).map(([name, s]) => `.text-${name} {
  font-family: var(--font-${name}-family);
  font-size: var(--font-${name}-size);
  font-weight: var(--font-${name}-weight);
  line-height: var(--font-${name}-line-height);
  letter-spacing: var(--font-${name}-letter-spacing);${s.uppercase ? '\n  text-transform: uppercase;' : ''}
}`).join('\n')

writeFileSync(join(dir, 'tokens.css'),
`/* GENERATED by build.mjs from tokens.json — do not edit. */
:root {
${css.join('\n')}
}

${textClasses}
`)

const camel = (s) => s.replace(/[-/](\w)/g, (_, c) => c.toUpperCase())
const obj = (o) => JSON.stringify(o, null, 2)
const colors = Object.fromEntries(Object.entries(t.color).map(([k, v]) => [camel(k), v]))
writeFileSync(join(dir, 'tokens.ts'),
`// GENERATED by build.mjs from tokens.json — do not edit.
export const color = ${obj(colors)} as const
export const space = ${obj(t.space)} as const
export const radius = ${obj(t.radius)} as const
export const breakpoint = ${obj(Object.fromEntries(Object.entries(t.breakpoint).filter(([k]) => !k.startsWith('$'))))} as const
export const layout = ${obj(Object.fromEntries(Object.entries(t.layout).filter(([k]) => !k.startsWith('$'))))} as const
`)
console.log('design tokens generated')
