// GENERATED by build.mjs from tokens.json — do not edit.
export const color = {
  "brandPrimary": "#ffc20e",
  "brandPrimarySoft": "#fff6dc",
  "brandPrimaryBorder": "#f5d573",
  "textPrimary": "#111827",
  "textSecondary": "#6b7280",
  "textTertiary": "#9aa1ac",
  "textBrand": "#8a5a00",
  "textOnBrand": "#111111",
  "textOnDark": "#e8e8e8",
  "textOnDarkMuted": "#a3a3a3",
  "bgSurface": "#ffffff",
  "bgSubtle": "#f6f6f8",
  "bgMuted": "#e6e7eb",
  "bgSidebar": "#151515",
  "bgSidebarRaised": "#202020",
  "borderDefault": "#e4e6eb",
  "borderSidebar": "#2b2b2b",
  "statusSuccess": "#22c55e",
  "statusWarning": "#b45309",
  "statusWarningSoft": "#fef0dc",
  "statusDanger": "#ef4444",
  "statusDangerSoft": "#fde6e6",
  "typeNormal": "#1a73e8",
  "typeNormalSoft": "#e0edff",
  "typeFridge": "#1e8e4a",
  "typeFridgeSoft": "#daf3e1",
  "typeVan": "#d93025",
  "typeVanSoft": "#fde6e6"
} as const
export const space = {
  "2": 2,
  "4": 4,
  "6": 6,
  "8": 8,
  "10": 10,
  "12": 12,
  "16": 16,
  "20": 20,
  "24": 24,
  "28": 28,
  "32": 32
} as const
export const radius = {
  "xs": 6,
  "sm": 8,
  "md": 12,
  "lg": 16,
  "full": 999
} as const
export const breakpoint = {
  "tablet": 768,
  "desktop": 1024,
  "wide": 1280
} as const
export const layout = {
  "sidebarWidth": 248,
  "navItemHeight": 40,
  "topBarHeight": 72
} as const
