import { expect, test } from '@playwright/test'

test.skip(process.env.MANUAL_PLANNING_FIXTURE !== 'synthetic', 'Requires isolated invented fixtures.')
const apiBase = process.env.API_URL ?? 'http://localhost:18084'

test('confirmed queue filters and deferrals stay correct after reload', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('USER ID', { exact: true }).fill('DSP-001')
  await page.getByLabel('PASSWORD', { exact: true }).fill(process.env.SEED_DISPATCHER_PASSWORD!)
  await page.getByRole('button', { name: 'Sign In', exact: true }).click()
  await expect(page).toHaveURL(/\/dispatcher$/)
  await page.goto('/dispatcher/planning')
  await expect(page.getByText('SYN001', { exact: true })).toBeVisible()
  await expect(page.getByText('SYN002', { exact: true })).toBeVisible()
  await expect(page.getByText(/2 confirmed orders · 1.9 m³/)).toBeVisible()
  await expect(page.getByText(/7 late orders/)).toHaveCount(0)
  await page.getByRole('button', { name: /van.only/i }).click()
  await expect(page.getByText('SYN001', { exact: true })).toBeVisible()
  await expect(page.getByText('SYN002', { exact: true })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Select order SYN001', exact: true }).check()
  await page.getByRole('button', { name: /move to deferred/i }).click()
  await page.getByLabel('Deferral reason', { exact: true }).fill('Synthetic browser capacity reason')
  await page.getByLabel('Next delivery date (optional)', { exact: true }).fill('2026-06-27')
  await page.getByRole('button', { name: 'Save deferral', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page).toHaveURL(/planId=\d+/)
  const id = new URL(page.url()).searchParams.get('planId')!
  const read = async () => (await page.request.get(`${apiBase}/api/v1/dispatcher/plans/${id}`)).json()
  const saved = await read()
  expect(saved.unassignedOrders).toHaveLength(2)
  expect(saved.unassignedOrders.find((item: { order: { orderRef: string } }) => item.order.orderRef === 'SYN001'))
    .toMatchObject({ disposition: 'DEFERRED', reason: 'Synthetic browser capacity reason', nextDeliveryDate: '2026-06-27' })
  await page.reload()
  expect(await read()).toEqual(saved)
  await expect(page.getByRole('heading', { name: new RegExp(`Plan #${id} Frozen`) })).toBeVisible()
  await page.screenshot({ path: '/tmp/waypoint-planning-integrity.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('combobox', { name: 'Depot', exact: true }).first().selectOption('Kandy')
  await expect(page).not.toHaveURL(/planId=/)
  await expect(page.getByRole('heading', { name: /Plan #\d+ Frozen/ })).toHaveCount(0)
  await expect(page.getByText('No confirmed orders', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Depot', exact: true }).first().selectOption('Peliyagoda')
  await expect(page.getByText('SYN001', { exact: true })).toBeVisible()
  await expect(page.getByText(/0 recorded deferrals/)).toBeVisible()
})
